task: detect
mode: train

epochs: 12
patience: 5
imgsz: 704
batch: 3
workers: 2
cache: false
optimizer: auto
seed: 42
deterministic: false
cos_lr: true
close_mosaic: 0
amp: true
multi_scale: 0.0
save: true
save_period: 2
plots: true
rect: true
val: true
split: val

lr0: 0.0008
lrf: 0.10
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 1.0
warmup_momentum: 0.8
warmup_bias_lr: 0.03
box: 7.5
cls: 0.35
cls_pw: 0.8
dfl: 1.5

hsv_h: 0.002
hsv_s: 0.12
hsv_v: 0.05
degrees: 0.0
translate: 0.02
scale: 0.08
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 0.0
mixup: 0.0
cutmix: 0.0
